//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KRisprav
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Вакансии.
    /// </summary>
    // *** Start programmer edit section *** (Вакансии CustomAttributes)

    // *** End programmer edit section *** (Вакансии CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ВакансииE", new string[] {
            "ТребуемыйОпыт as \'Требуемый опыт\'",
            "Образование as \'Образование\'",
            "ДатаСоздания as \'Дата создания\'",
            "Должность as \'Должность\'",
            "Должность.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Должность.Наименование"})]
    [MasterViewDefineAttribute("ВакансииE", "Должность", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("ВакансииL", new string[] {
            "ТребуемыйОпыт as \'Требуемый опыт\'",
            "Образование as \'Образование\'",
            "ДатаСоздания as \'Дата создания\'",
            "Должность.Наименование as \'Наименование\'"})]
    public class Вакансии : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.KRisprav.Опыт fТребуемыйОпыт;
        
        private IIS.KRisprav.ВидОбразования fОбразование;
        
        private System.DateTime fДатаСоздания = System.DateTime.Now;
        
        private IIS.KRisprav.Должность fДолжность;
        
        // *** Start programmer edit section *** (Вакансии CustomMembers)

        // *** End programmer edit section *** (Вакансии CustomMembers)

        
        /// <summary>
        /// ДатаСоздания.
        /// </summary>
        // *** Start programmer edit section *** (Вакансии.ДатаСоздания CustomAttributes)

        // *** End programmer edit section *** (Вакансии.ДатаСоздания CustomAttributes)
        public virtual System.DateTime ДатаСоздания
        {
            get
            {
                // *** Start programmer edit section *** (Вакансии.ДатаСоздания Get start)

                // *** End programmer edit section *** (Вакансии.ДатаСоздания Get start)
                System.DateTime result = this.fДатаСоздания;
                // *** Start programmer edit section *** (Вакансии.ДатаСоздания Get end)

                // *** End programmer edit section *** (Вакансии.ДатаСоздания Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Вакансии.ДатаСоздания Set start)

                // *** End programmer edit section *** (Вакансии.ДатаСоздания Set start)
                this.fДатаСоздания = value;
                // *** Start programmer edit section *** (Вакансии.ДатаСоздания Set end)

                // *** End programmer edit section *** (Вакансии.ДатаСоздания Set end)
            }
        }
        
        /// <summary>
        /// Образование.
        /// </summary>
        // *** Start programmer edit section *** (Вакансии.Образование CustomAttributes)

        // *** End programmer edit section *** (Вакансии.Образование CustomAttributes)
        public virtual IIS.KRisprav.ВидОбразования Образование
        {
            get
            {
                // *** Start programmer edit section *** (Вакансии.Образование Get start)

                // *** End programmer edit section *** (Вакансии.Образование Get start)
                IIS.KRisprav.ВидОбразования result = this.fОбразование;
                // *** Start programmer edit section *** (Вакансии.Образование Get end)

                // *** End programmer edit section *** (Вакансии.Образование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Вакансии.Образование Set start)

                // *** End programmer edit section *** (Вакансии.Образование Set start)
                this.fОбразование = value;
                // *** Start programmer edit section *** (Вакансии.Образование Set end)

                // *** End programmer edit section *** (Вакансии.Образование Set end)
            }
        }
        
        /// <summary>
        /// ТребуемыйОпыт.
        /// </summary>
        // *** Start programmer edit section *** (Вакансии.ТребуемыйОпыт CustomAttributes)

        // *** End programmer edit section *** (Вакансии.ТребуемыйОпыт CustomAttributes)
        public virtual IIS.KRisprav.Опыт ТребуемыйОпыт
        {
            get
            {
                // *** Start programmer edit section *** (Вакансии.ТребуемыйОпыт Get start)

                // *** End programmer edit section *** (Вакансии.ТребуемыйОпыт Get start)
                IIS.KRisprav.Опыт result = this.fТребуемыйОпыт;
                // *** Start programmer edit section *** (Вакансии.ТребуемыйОпыт Get end)

                // *** End programmer edit section *** (Вакансии.ТребуемыйОпыт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Вакансии.ТребуемыйОпыт Set start)

                // *** End programmer edit section *** (Вакансии.ТребуемыйОпыт Set start)
                this.fТребуемыйОпыт = value;
                // *** Start programmer edit section *** (Вакансии.ТребуемыйОпыт Set end)

                // *** End programmer edit section *** (Вакансии.ТребуемыйОпыт Set end)
            }
        }
        
        /// <summary>
        /// Вакансии.
        /// </summary>
        // *** Start programmer edit section *** (Вакансии.Должность CustomAttributes)

        // *** End programmer edit section *** (Вакансии.Должность CustomAttributes)
        [PropertyStorage(new string[] {
                "Должность"})]
        [NotNull()]
        public virtual IIS.KRisprav.Должность Должность
        {
            get
            {
                // *** Start programmer edit section *** (Вакансии.Должность Get start)

                // *** End programmer edit section *** (Вакансии.Должность Get start)
                IIS.KRisprav.Должность result = this.fДолжность;
                // *** Start programmer edit section *** (Вакансии.Должность Get end)

                // *** End programmer edit section *** (Вакансии.Должность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Вакансии.Должность Set start)

                // *** End programmer edit section *** (Вакансии.Должность Set start)
                this.fДолжность = value;
                // *** Start programmer edit section *** (Вакансии.Должность Set end)

                // *** End programmer edit section *** (Вакансии.Должность Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ВакансииE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВакансииE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВакансииE", typeof(IIS.KRisprav.Вакансии));
                }
            }
            
            /// <summary>
            /// "ВакансииL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВакансииL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВакансииL", typeof(IIS.KRisprav.Вакансии));
                }
            }
        }
    }
}
