//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KRisprav
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Вид образования.
    /// </summary>
    // *** Start programmer edit section *** (ВидОбразования CustomAttributes)

    // *** End programmer edit section *** (ВидОбразования CustomAttributes)
    public enum ВидОбразования
    {
        
        // *** Start programmer edit section *** (ВидОбразования.Среднее CustomAttributes)

        // *** End programmer edit section *** (ВидОбразования.Среднее CustomAttributes)
        [Caption("Среднее")]
        Среднее,
        
        // *** Start programmer edit section *** (ВидОбразования.СПО CustomAttributes)

        // *** End programmer edit section *** (ВидОбразования.СПО CustomAttributes)
        [Caption("СПО")]
        СПО,
        
        // *** Start programmer edit section *** (ВидОбразования.Высшее CustomAttributes)

        // *** End programmer edit section *** (ВидОбразования.Высшее CustomAttributes)
        [Caption("Высшее")]
        Высшее,
    }
}
