//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KRisprav
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Действия.
    /// </summary>
    // *** Start programmer edit section *** (Действия CustomAttributes)

    // *** End programmer edit section *** (Действия CustomAttributes)
    public enum Действия
    {
        
        // *** Start programmer edit section *** (Действия.Печать CustomAttributes)

        // *** End programmer edit section *** (Действия.Печать CustomAttributes)
        [Caption("Печать")]
        Печать,
        
        // *** Start programmer edit section *** (Действия.ЭлПочта CustomAttributes)

        // *** End programmer edit section *** (Действия.ЭлПочта CustomAttributes)
        [Caption("ЭлПочта")]
        ЭлПочта,
    }
}
