//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KRisprav
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Командировка.
    /// </summary>
    // *** Start programmer edit section *** (Командировка CustomAttributes)

    // *** End programmer edit section *** (Командировка CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КомандировкаE", new string[] {
            "ДатаЗаполнения as \'Дата заполнения\'",
            "НомерДокумента as \'Номер документа\'",
            "МестоНазначения as \'Место назначения\'",
            "Цель as \'Цель\'",
            "КолвоДней as \'Колво дней\'",
            "Действие as \'Действие\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Сотрудники.ФИО"})]
    [AssociatedDetailViewAttribute("КомандировкаE", "Период", "ПериодE", true, "", "Период", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("КомандировкаE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("КомандировкаL", new string[] {
            "ДатаЗаполнения as \'Дата заполнения\'",
            "НомерДокумента as \'Номер документа\'",
            "МестоНазначения as \'Место назначения\'",
            "Цель as \'Цель\'",
            "КолвоДней as \'Колво дней\'",
            "Действие as \'Действие\'",
            "Сотрудники.ФИО as \'ФИО\'"})]
    public class Командировка : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаЗаполнения = System.DateTime.Now;
        
        private int fНомерДокумента;
        
        private string fМестоНазначения;
        
        private string fЦель;
        
        private int fКолвоДней;
        
        private IIS.KRisprav.Действия fДействие;
        
        private IIS.KRisprav.Сотрудники fСотрудники;
        
        private IIS.KRisprav.DetailArrayOfПериод fПериод;
        
        // *** Start programmer edit section *** (Командировка CustomMembers)

        // *** End programmer edit section *** (Командировка CustomMembers)

        
        /// <summary>
        /// ДатаЗаполнения.
        /// </summary>
        // *** Start programmer edit section *** (Командировка.ДатаЗаполнения CustomAttributes)

        // *** End programmer edit section *** (Командировка.ДатаЗаполнения CustomAttributes)
        public virtual System.DateTime ДатаЗаполнения
        {
            get
            {
                // *** Start programmer edit section *** (Командировка.ДатаЗаполнения Get start)

                // *** End programmer edit section *** (Командировка.ДатаЗаполнения Get start)
                System.DateTime result = this.fДатаЗаполнения;
                // *** Start programmer edit section *** (Командировка.ДатаЗаполнения Get end)

                // *** End programmer edit section *** (Командировка.ДатаЗаполнения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Командировка.ДатаЗаполнения Set start)

                // *** End programmer edit section *** (Командировка.ДатаЗаполнения Set start)
                this.fДатаЗаполнения = value;
                // *** Start programmer edit section *** (Командировка.ДатаЗаполнения Set end)

                // *** End programmer edit section *** (Командировка.ДатаЗаполнения Set end)
            }
        }
        
        /// <summary>
        /// Действие.
        /// </summary>
        // *** Start programmer edit section *** (Командировка.Действие CustomAttributes)

        // *** End programmer edit section *** (Командировка.Действие CustomAttributes)
        public virtual IIS.KRisprav.Действия Действие
        {
            get
            {
                // *** Start programmer edit section *** (Командировка.Действие Get start)

                // *** End programmer edit section *** (Командировка.Действие Get start)
                IIS.KRisprav.Действия result = this.fДействие;
                // *** Start programmer edit section *** (Командировка.Действие Get end)

                // *** End programmer edit section *** (Командировка.Действие Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Командировка.Действие Set start)

                // *** End programmer edit section *** (Командировка.Действие Set start)
                this.fДействие = value;
                // *** Start programmer edit section *** (Командировка.Действие Set end)

                // *** End programmer edit section *** (Командировка.Действие Set end)
            }
        }
        
        /// <summary>
        /// КолвоДней.
        /// </summary>
        // *** Start programmer edit section *** (Командировка.КолвоДней CustomAttributes)

        // *** End programmer edit section *** (Командировка.КолвоДней CustomAttributes)
        public virtual int КолвоДней
        {
            get
            {
                // *** Start programmer edit section *** (Командировка.КолвоДней Get start)

                // *** End programmer edit section *** (Командировка.КолвоДней Get start)
                int result = this.fКолвоДней;
                // *** Start programmer edit section *** (Командировка.КолвоДней Get end)

                // *** End programmer edit section *** (Командировка.КолвоДней Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Командировка.КолвоДней Set start)

                // *** End programmer edit section *** (Командировка.КолвоДней Set start)
                this.fКолвоДней = value;
                // *** Start programmer edit section *** (Командировка.КолвоДней Set end)

                // *** End programmer edit section *** (Командировка.КолвоДней Set end)
            }
        }
        
        /// <summary>
        /// МестоНазначения.
        /// </summary>
        // *** Start programmer edit section *** (Командировка.МестоНазначения CustomAttributes)

        // *** End programmer edit section *** (Командировка.МестоНазначения CustomAttributes)
        [StrLen(255)]
        public virtual string МестоНазначения
        {
            get
            {
                // *** Start programmer edit section *** (Командировка.МестоНазначения Get start)

                // *** End programmer edit section *** (Командировка.МестоНазначения Get start)
                string result = this.fМестоНазначения;
                // *** Start programmer edit section *** (Командировка.МестоНазначения Get end)

                // *** End programmer edit section *** (Командировка.МестоНазначения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Командировка.МестоНазначения Set start)

                // *** End programmer edit section *** (Командировка.МестоНазначения Set start)
                this.fМестоНазначения = value;
                // *** Start programmer edit section *** (Командировка.МестоНазначения Set end)

                // *** End programmer edit section *** (Командировка.МестоНазначения Set end)
            }
        }
        
        /// <summary>
        /// НомерДокумента.
        /// </summary>
        // *** Start programmer edit section *** (Командировка.НомерДокумента CustomAttributes)

        // *** End programmer edit section *** (Командировка.НомерДокумента CustomAttributes)
        public virtual int НомерДокумента
        {
            get
            {
                // *** Start programmer edit section *** (Командировка.НомерДокумента Get start)

                // *** End programmer edit section *** (Командировка.НомерДокумента Get start)
                int result = this.fНомерДокумента;
                // *** Start programmer edit section *** (Командировка.НомерДокумента Get end)

                // *** End programmer edit section *** (Командировка.НомерДокумента Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Командировка.НомерДокумента Set start)

                // *** End programmer edit section *** (Командировка.НомерДокумента Set start)
                this.fНомерДокумента = value;
                // *** Start programmer edit section *** (Командировка.НомерДокумента Set end)

                // *** End programmer edit section *** (Командировка.НомерДокумента Set end)
            }
        }
        
        /// <summary>
        /// Цель.
        /// </summary>
        // *** Start programmer edit section *** (Командировка.Цель CustomAttributes)

        // *** End programmer edit section *** (Командировка.Цель CustomAttributes)
        [StrLen(255)]
        public virtual string Цель
        {
            get
            {
                // *** Start programmer edit section *** (Командировка.Цель Get start)

                // *** End programmer edit section *** (Командировка.Цель Get start)
                string result = this.fЦель;
                // *** Start programmer edit section *** (Командировка.Цель Get end)

                // *** End programmer edit section *** (Командировка.Цель Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Командировка.Цель Set start)

                // *** End programmer edit section *** (Командировка.Цель Set start)
                this.fЦель = value;
                // *** Start programmer edit section *** (Командировка.Цель Set end)

                // *** End programmer edit section *** (Командировка.Цель Set end)
            }
        }
        
        /// <summary>
        /// Командировка.
        /// </summary>
        // *** Start programmer edit section *** (Командировка.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (Командировка.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.KRisprav.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (Командировка.Сотрудники Get start)

                // *** End programmer edit section *** (Командировка.Сотрудники Get start)
                IIS.KRisprav.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (Командировка.Сотрудники Get end)

                // *** End programmer edit section *** (Командировка.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Командировка.Сотрудники Set start)

                // *** End programmer edit section *** (Командировка.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (Командировка.Сотрудники Set end)

                // *** End programmer edit section *** (Командировка.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Командировка.
        /// </summary>
        // *** Start programmer edit section *** (Командировка.Период CustomAttributes)

        // *** End programmer edit section *** (Командировка.Период CustomAttributes)
        public virtual IIS.KRisprav.DetailArrayOfПериод Период
        {
            get
            {
                // *** Start programmer edit section *** (Командировка.Период Get start)

                // *** End programmer edit section *** (Командировка.Период Get start)
                if ((this.fПериод == null))
                {
                    this.fПериод = new IIS.KRisprav.DetailArrayOfПериод(this);
                }
                IIS.KRisprav.DetailArrayOfПериод result = this.fПериод;
                // *** Start programmer edit section *** (Командировка.Период Get end)

                // *** End programmer edit section *** (Командировка.Период Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Командировка.Период Set start)

                // *** End programmer edit section *** (Командировка.Период Set start)
                this.fПериод = value;
                // *** Start programmer edit section *** (Командировка.Период Set end)

                // *** End programmer edit section *** (Командировка.Период Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КомандировкаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КомандировкаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КомандировкаE", typeof(IIS.KRisprav.Командировка));
                }
            }
            
            /// <summary>
            /// "КомандировкаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КомандировкаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КомандировкаL", typeof(IIS.KRisprav.Командировка));
                }
            }
        }
    }
}
