//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KRisprav
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Опыт.
    /// </summary>
    // *** Start programmer edit section *** (Опыт CustomAttributes)

    // *** End programmer edit section *** (Опыт CustomAttributes)
    public enum Опыт
    {
        
        // *** Start programmer edit section *** (Опыт.НеТребуется CustomAttributes)

        // *** End programmer edit section *** (Опыт.НеТребуется CustomAttributes)
        [Caption("НеТребуется")]
        НеТребуется,
        
        // *** Start programmer edit section *** (Опыт.Отгода CustomAttributes)

        // *** End programmer edit section *** (Опыт.Отгода CustomAttributes)
        [Caption("От1года")]
        Отгода,
        
        // *** Start programmer edit section *** (Опыт.ОтТлет CustomAttributes)

        // *** End programmer edit section *** (Опыт.ОтТлет CustomAttributes)
        [Caption("От3лет")]
        ОтТлет,
        
        // *** Start programmer edit section *** (Опыт.ОтШлет CustomAttributes)

        // *** End programmer edit section *** (Опыт.ОтШлет CustomAttributes)
        [Caption("От6лет")]
        ОтШлет,
    }
}
