//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KRisprav
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Период.
    /// </summary>
    // *** Start programmer edit section *** (Период CustomAttributes)

    // *** End programmer edit section *** (Период CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПериодE", new string[] {
            "Начало as \'Начало\'",
            "Конец as \'Конец\'"})]
    public class Период : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fНачало;
        
        private System.DateTime fКонец;
        
        private IIS.KRisprav.Командировка fКомандировка;
        
        // *** Start programmer edit section *** (Период CustomMembers)

        // *** End programmer edit section *** (Период CustomMembers)

        
        /// <summary>
        /// Конец.
        /// </summary>
        // *** Start programmer edit section *** (Период.Конец CustomAttributes)

        // *** End programmer edit section *** (Период.Конец CustomAttributes)
        public virtual System.DateTime Конец
        {
            get
            {
                // *** Start programmer edit section *** (Период.Конец Get start)

                // *** End programmer edit section *** (Период.Конец Get start)
                System.DateTime result = this.fКонец;
                // *** Start programmer edit section *** (Период.Конец Get end)

                // *** End programmer edit section *** (Период.Конец Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Период.Конец Set start)

                // *** End programmer edit section *** (Период.Конец Set start)
                this.fКонец = value;
                // *** Start programmer edit section *** (Период.Конец Set end)

                // *** End programmer edit section *** (Период.Конец Set end)
            }
        }
        
        /// <summary>
        /// Начало.
        /// </summary>
        // *** Start programmer edit section *** (Период.Начало CustomAttributes)

        // *** End programmer edit section *** (Период.Начало CustomAttributes)
        public virtual System.DateTime Начало
        {
            get
            {
                // *** Start programmer edit section *** (Период.Начало Get start)

                // *** End programmer edit section *** (Период.Начало Get start)
                System.DateTime result = this.fНачало;
                // *** Start programmer edit section *** (Период.Начало Get end)

                // *** End programmer edit section *** (Период.Начало Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Период.Начало Set start)

                // *** End programmer edit section *** (Период.Начало Set start)
                this.fНачало = value;
                // *** Start programmer edit section *** (Период.Начало Set end)

                // *** End programmer edit section *** (Период.Начало Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.KRisprav.Командировка.
        /// </summary>
        // *** Start programmer edit section *** (Период.Командировка CustomAttributes)

        // *** End programmer edit section *** (Период.Командировка CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Командировка"})]
        public virtual IIS.KRisprav.Командировка Командировка
        {
            get
            {
                // *** Start programmer edit section *** (Период.Командировка Get start)

                // *** End programmer edit section *** (Период.Командировка Get start)
                IIS.KRisprav.Командировка result = this.fКомандировка;
                // *** Start programmer edit section *** (Период.Командировка Get end)

                // *** End programmer edit section *** (Период.Командировка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Период.Командировка Set start)

                // *** End programmer edit section *** (Период.Командировка Set start)
                this.fКомандировка = value;
                // *** Start programmer edit section *** (Период.Командировка Set end)

                // *** End programmer edit section *** (Период.Командировка Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПериодE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПериодE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПериодE", typeof(IIS.KRisprav.Период));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Период.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfПериод CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfПериод CustomAttributes)
    public class DetailArrayOfПериод : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.KRisprav.DetailArrayOfПериод members)

        // *** End programmer edit section *** (IIS.KRisprav.DetailArrayOfПериод members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Период by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Период.
        /// </summary>
        public DetailArrayOfПериод(IIS.KRisprav.Командировка fКомандировка) : 
                base(typeof(Период), ((ICSSoft.STORMNET.DataObject)(fКомандировка)))
        {
        }
        
        public IIS.KRisprav.Период this[int index]
        {
            get
            {
                return ((IIS.KRisprav.Период)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.KRisprav.Период dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
